/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    NestableNFT: {
      address: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ChildAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "ChildIndexOutOfRange",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721AddressZeroIsNotaValidOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721ApprovalToCurrentOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721ApproveCallerIsNotOwnerNorApprovedForAll",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721ApproveToCaller",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721InvalidTokenId",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721MintToTheZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721NotApprovedOrOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TokenAlreadyMinted",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TransferFromIncorrectOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TransferToNonReceiverImplementer",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TransferToTheZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "IdZeroForbidden",
          type: "error",
        },
        {
          inputs: [],
          name: "IsNotContract",
          type: "error",
        },
        {
          inputs: [],
          name: "MaxPendingChildrenReached",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "childContract",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "MaxRecursiveBurnsReached",
          type: "error",
        },
        {
          inputs: [],
          name: "MintToNonNestableImplementer",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTooDeep",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTransferToDescendant",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTransferToNonNestableImplementer",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTransferToSelf",
          type: "error",
        },
        {
          inputs: [],
          name: "NotApprovedOrDirectOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "PendingChildIndexOutOfRange",
          type: "error",
        },
        {
          inputs: [],
          name: "UnexpectedChildId",
          type: "error",
        },
        {
          inputs: [],
          name: "UnexpectedNumberOfChildren",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "AllChildrenRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "approved",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "ChildAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "ChildProposed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "fromPending",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "toZero",
              type: "bool",
            },
          ],
          name: "ChildTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fromTokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "toTokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "NestTransfer",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "acceptChild",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "addChild",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxChildrenBurns",
              type: "uint256",
            },
          ],
          name: "burn",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "childOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "childrenOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "directOwnerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getApproved",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
          ],
          name: "nestMint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
          ],
          name: "nestTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "nestTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ownerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "pendingChildOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "pendingChildrenOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxRejections",
              type: "uint256",
            },
          ],
          name: "rejectAllChildren",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "showTreeOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPending",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "transferChild",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    NestableNFT2: {
      address: "0x68B1D87F95878fE05B998F19b66F4baba5De1aed",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ChildAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "ChildIndexOutOfRange",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721AddressZeroIsNotaValidOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721ApprovalToCurrentOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721ApproveCallerIsNotOwnerNorApprovedForAll",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721ApproveToCaller",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721InvalidTokenId",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721MintToTheZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721NotApprovedOrOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TokenAlreadyMinted",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TransferFromIncorrectOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TransferToNonReceiverImplementer",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC721TransferToTheZeroAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "IdZeroForbidden",
          type: "error",
        },
        {
          inputs: [],
          name: "IsNotContract",
          type: "error",
        },
        {
          inputs: [],
          name: "MaxPendingChildrenReached",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "childContract",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "MaxRecursiveBurnsReached",
          type: "error",
        },
        {
          inputs: [],
          name: "MintToNonNestableImplementer",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTooDeep",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTransferToDescendant",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTransferToNonNestableImplementer",
          type: "error",
        },
        {
          inputs: [],
          name: "NestableTransferToSelf",
          type: "error",
        },
        {
          inputs: [],
          name: "NotApprovedOrDirectOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "PendingChildIndexOutOfRange",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "length",
              type: "uint256",
            },
          ],
          name: "StringsInsufficientHexLength",
          type: "error",
        },
        {
          inputs: [],
          name: "UnexpectedChildId",
          type: "error",
        },
        {
          inputs: [],
          name: "UnexpectedNumberOfChildren",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "AllChildrenRejected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "approved",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "ChildAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "ChildProposed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "fromPending",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "toZero",
              type: "bool",
            },
          ],
          name: "ChildTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fromTokenId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "toTokenId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "NestTransfer",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
          ],
          name: "acceptChild",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "addChild",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxChildrenBurns",
              type: "uint256",
            },
          ],
          name: "burn",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "childOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "childrenOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "directOwnerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getApproved",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
          ],
          name: "nestMint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
          ],
          name: "nestTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "nestTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ownerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "pendingChildOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "pendingChildrenOf",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "tokenId",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "contractAddress",
                  type: "address",
                },
              ],
              internalType: "struct IERC7401.Child[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxRejections",
              type: "uint256",
            },
          ],
          name: "rejectAllChildren",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "parentId",
              type: "uint256",
            },
          ],
          name: "showTreeOf",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "destinationId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "childIndex",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "childId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPending",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "transferChild",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
